const config = {
  locales: [
    'zh-Hans',
    'zh',
  ],
  translations: {
    'zh-Hans': {
      'app.components.LeftMenu.navbrand.title': 'Bag 管理后台',
      'app.components.LeftMenu.navbrand.workplace': '内容工作台',
      'plugin.users-permissions.auth.user.displayName': '用户管理',
      'users-permissions.user.api.name': '用户管理',
      'users-permissions.user.api.name.plural': '用户管理',
      'user.api.name': '用户管理',
      'user.api.name.plural': '用户管理',
      'Users': '用户管理',
      'User': '用户管理',
      'captcha.api.name': '验证码管理',
      'Captcha': '验证码管理',
      'refresh-token.api.name': '刷新令牌管理',
      'Refresh Token': '刷新令牌管理',
      'article.api.name': '文章管理',
      'Article': '文章管理',
      'category.api.name': '分类管理',
      'Category': '分类管理',
      'tag.api.name': '标签管理',
      'Tag': '标签管理',
      'menu.api.name': '菜单管理',
      'Menu': '菜单管理',
      'menu-item.api.name': '菜单项管理',
      'Menu Item': '菜单项管理',
      'comment.api.name': '评论管理',
      'Comment': '评论管理',
      'banner.api.name': '幻灯片管理',
      'Banner': '幻灯片管理',
      'friend-link.api.name': '友情链接管理',
      'Friend Link': '友情链接管理',
      'page.api.name': '单页管理',
      'Page': '单页管理',
      'message.api.name': '留言板管理',
      'Message': '留言板管理',
      'log.api.name': '升级日志',
      'Log': '升级日志',
      'pending': '⏳ 待审核',
      'approved': '✅ 已通过',
      'rejected': '❌ 已拒绝',
    },
    'zh': {
      'app.components.LeftMenu.navbrand.title': 'Bag 管理后台',
      'app.components.LeftMenu.navbrand.workplace': '内容工作台',
      'plugin.users-permissions.auth.user.displayName': '用户管理',
      'users-permissions.user.api.name': '用户管理',
      'users-permissions.user.api.name.plural': '用户管理',
      'user.api.name': '用户管理',
      'user.api.name.plural': '用户管理',
      'Users': '用户管理',
      'User': '用户管理',
      'captcha.api.name': '验证码管理',
      'Captcha': '验证码管理',
      'refresh-token.api.name': '刷新令牌管理',
      'Refresh Token': '刷新令牌管理',
      'article.api.name': '文章管理',
      'Article': '文章管理',
      'category.api.name': '分类管理',
      'Category': '分类管理',
      'tag.api.name': '标签管理',
      'Tag': '标签管理',
      'menu.api.name': '菜单管理',
      'Menu': '菜单管理',
      'menu-item.api.name': '菜单项管理',
      'Menu Item': '菜单项管理',
      'comment.api.name': '评论管理',
      'Comment': '评论管理',
      'banner.api.name': '幻灯片管理',
      'Banner': '幻灯片管理',
      'friend-link.api.name': '友情链接管理',
      'Friend Link': '友情链接管理',
      'page.api.name': '单页管理',
      'Page': '单页管理',
      'message.api.name': '留言板管理',
      'Message': '留言板管理',
      'log.api.name': '升级日志',
      'Log': '升级日志',
      'pending': '⏳ 待审核',
      'approved': '✅ 已通过',
      'rejected': '❌ 已拒绝',
    },
  },
};

const bootstrap = (app) => {
  console.log(app);
};

export default {
  config,
  bootstrap,
};
